CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	email VARCHAR(256) UNIQUE NOT NULL,
	password VARCHAR(128) NOT NULL,
	first_name VARCHAR(64) NOT NULL,
	last_name VARCHAR(64) NOT NULL,
	permission SMALLINT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
	id SERIAL PRIMARY KEY,
	customer INTEGER REFERENCES users(id) NOT NULL,
	product VARCHAR(512) NOT NULL,
	price DECIMAL NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS results (
	id SERIAL PRIMARY KEY,
	type VARCHAR(64) NOT NULL,
	protein INTEGER,
	fat INTEGER,
	carbs INTEGER,
	fiber INTEGER,
	suggested_calories INTEGER,
	bmr INTEGER,
	tdee INTEGER,
	customer INTEGER REFERENCES users(id) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);